name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/eks-scanner-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Determine if pre-release
        id: precheck
        run: |
          TAG="${GITHUB_REF##*/}"
          echo "Tag: $TAG"
          MAJOR=$(echo "$TAG" | sed -E 's/^v([0-9]+).*/\1/')
          if [ "$MAJOR" -eq 0 ]; then
            echo "is_prerelease=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_prerelease=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/eks-scanner-*
          prerelease: ${{ steps.precheck.outputs.is_prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
